config/routes.rb
RecipeBook::Application.routes.draw do

  devise_for :users

resources :welcome_mailer do
 collection do
  post 'welcome'
 end
end 

resources :items do 
  collection do
    get '_dashboard'
    get 'list_recipe'
    get '_panel'
    post 'mailer'
    get 'like_count'
  end
end
  resources :admin do
    collection do
      get 'items'
      get 'home'
      get 'categories'
      get 'list_recipe'
      get 'show'
      get 'my_recipe'
      get '_panel'
      
    end
  end

 resources :recipes do
   collection do
     get 'view_category'
     get 'view_recipe'
     get 'home'
     get 'my_recipe'
     get 'profile'
     post 'updateprofile'
     get '_search'
   end
 end

  resources :categories do
    collection do
      get 'home'
    end
  end

 

  

end

app/views/admin/_create.html.erb
<%= tinymce_assets %><%= tinymce %>
<%= form_for @item  , :html => { :multipart => true } do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="form-group">
    <%= f.label :category %><br />
  <%= collection_select(:item, :category_id, Category.all, :id, :name, {:prompt => false } , {:class=>"form-control"}) %>
   </div>
  <div class="form-group">
    <%= f.label :item_name %><br />
    <%= f.text_field :item_name , :class=>"form-control" %>
  </div>
 <div class="form-group">
    <%= f.label :pic %><br />
    <%= f.file_field :pic  %>
  </div>
 <div class="form-group">
    <%= f.label :description %><br />
    <%= f.text_area :description , :class=>"tinymce", :rows=>9 , :cols=>29 %>
  </div>
   <div class="actions">
    <%= submit_tag "CREATE RECIPE" , :class=>"btn btn-warning"%>
  </div>
<% end %>

app/views/admin/_form.html.erb
<%= tinymce_assets %><%= tinymce %> <%= form_for @item , :url => admin_path(@item) , :method=>"put", :html => { :multipart => true } do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="field">
    <%= f.label :category %><br />
    <%= collection_select(:item, :category_id, Category.all, :id, :name, {:prompt => false })  %>
   </div>
  <div class="field">
    <%= f.label :item_name %><br />
    <%= f.text_field :item_name %>
  </div>
 <div class="field">
    <%= f.label :pic %><br />
    <%= f.file_field :pic %>
  </div>
 <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description , :class=>"tinymce", :rows=>9 , :cols=>29 %>
  </div>
   <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/_panel.html.erb
<div class="panel panel-warning">
<h5>
<%= link_to '<- My Recipies', my_recipe_admin_index_path %> | 
<%= link_to 'Edit', edit_admin_path(@item) %> |
<%= link_to 'Destroy', @item , method: :delete, data: { confirm: 'Are you sure?' } %>
  </h5>
</div>

app/views/admin/categories.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/admin/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

app/views/admin/home.html.erb
<div class="wrapper">
     <div id="pics">
      <% @new_recipe.each do |recipe| %>
 
     <img src="<%= recipe.pic %>" title="<%= recipe.item_name %>" /> 
     
      <% end %>
     </div>
<div class="ribbon-wrapper-green">
<div class="ribbon-green">NEW</div>
   </div>
 </div>    
        
    

app/views/admin/index.html.erb
<%= render 'dashboard' %> <h1>Recipies</h1>

<table>
  

<% @items.each do |item| %>
  <tr>
   <ul>
    <td>
    <li><h3><%= link_to "#{item.item_name}" , item_path(item.id) %></h3></li>
   </td>
   </ul>
  </tr>
<% end %>
</table>

<br />

app/views/admin/items.html.erb
<h1>Listing Recipies</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.item_name %></td>
    <td><%= link_to 'Show' , admin_path(:id => item) %></td>
    <td><%= link_to 'Edit', edit_admin_path(item) %></td>
    <td><%= link_to 'Destroy', item , method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/admin/list_recipe.html.erb
<h2> <%= @category.name  %> Recipies </h2>
<h4>

<ul class="vmenu">

<% @recipe.each do |recipe| %>
<li>
 <%= link_to "#{recipe.item_name}" , admin_path(recipe.id) %> </a>
</li>
<% end %>

</ul>

</h4>

app/views/admin/my_recipe.html.erb
<% if @recipe.empty? %>
<h2> No recipies Yet </h2>
<% end %>

<h2> My Recipies </h2>

<ul>
<% @recipe.each do |recipe| %>

<h3>
<li><%= link_to "#{recipe.item_name}" , admin_path(:id => recipe) %></li>
</h3>
<% end %>
</ul>

app/views/admin/new.html.erb
<h1>New Recipe</h1>

<%= render 'create' %>

app/views/admin/show.html.erb
<hr>
<ol class="breadcrumb">
<li><a href="/admin/categories">< Choose Category</a></li>

</ol>
<p id="notice"><%= notice %></p>

<%= render 'panel' %>

<b>Name:</b>
<%= @item.item_name %><br><br>
<b>Pic:</b>  <%= image_tag(@item.pic.url) %><br><br>
<b>Description:</b> <%= @item.description %><br><br>