config/routes.rb
RecipeBook::Application.routes.draw do

  devise_for :users

resources :welcome_mailer do
 collection do
  post 'welcome'
 end
end 

resources :items do 
  collection do
    get '_dashboard'
    get 'list_recipe'
    get '_panel'
    post 'mailer'
    get 'like_count'
  end
end
  resources :admin do
    collection do
      get 'items'
      get 'home'
      get 'categories'
      get 'list_recipe'
      get 'show'
      get 'my_recipe'
      get '_panel'
      
    end
  end

 resources :recipes do
   collection do
     get 'view_category'
     get 'view_recipe'
     get 'home'
     get 'my_recipe'
     get 'profile'
     post 'updateprofile'
     get '_search'
   end
 end

  resources :categories do
    collection do
      get 'home'
    end
  end

 

  

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController


def home 
 @new_recipe=Item.find(:all , :order => "created_at DESC", :limit => 3)
 @most_liked=Item.find(:all , :order => "likes DESC" , :limit => 3)
end

def view_category
  @categories= Category.all
end

def view_recipe
  @item= Item.all
end

def my_recipe
  if current_user
  @recipe = Item.where(:user_id => current_user.id)
end
end

def profile
 if !current_user
  redirect_to home_recipes_path , :notice=>"Log in to view profile!"
 end
end

def updateprofile
 @email=params[:email]
 @address=params[:address]
 @hobbies=params[:hobbies]
 @pic=params[:pic]
 @user= User.where(:email=>current_user.email)
 if @user
 @user.update_all(:address => @address , :email=>@email , :hobbies =>@hobbies)
 
 end
end

end

app/views/recipes/__search.html.erb
<script>
    $(document).ready(function() {
        var availableTags = <%= Item.all.map(&:item_name).to_json.html_safe %>;
        $("#search" ).autocomplete({
            source: availableTags
        });
    });
</script>

<%= form_tag("/items" , :method=>"get" ) do   %>
    <div class="col-xs-4">

   <input type="search" name="search" id="search"  class="form-control" placeholder="Search Products"/>

      <div class="btn-group-sm">
        <button type="submit" class="btn btn-warning" id="search_btn">SEARCH</button>
      </div>
    </div>
<% end %>

app/views/recipes/home.html.erb
<div class="panel panel-warning">
  <div class="panel-heading">
    <b>TOP RATED RECIPES</b>
  </div>
  <div class="panel-body">
  <table>
 <% @most_liked.each do |recipe| %>
 <tr>
 <th style="border:2px solid whitesmoke"><%= image_tag recipe.pic.url(:thumb) %></th>
 <th><%= link_to recipe.item_name , item_path(:id=>recipe.id) %></th>
 </tr>
 <% end %>
 </table>
 </div>
</div>


<br>
<div class="wrapper">
 <div id="pics"> 
  <% @new_recipe.each do |recipe| %>
 <img src="<%= recipe.pic %>" /> 
 <% end %>
 </div>
  <div class="ribbon-wrapper-green">
  <div class="ribbon-green">NEW</div>
  </div>
</div>

<br><br>

app/views/recipes/my_recipe.html.erb
<% if @recipe.nil? %>
<h2> No recipies Yet </h2>
<% end %>
<% if current_user %>
<h2> My Recipies </h2>
<ul>
<% @recipe.each do |recipe| %>
<h3>
<li><%= link_to "#{recipe.item_name}" , item_path(:id => recipe) %></li>
</h3>
<% end %>
</ul>
<% else %>
<p class="notice"> Log in to create recipe ! </p>
<% end %>

app/views/recipes/profile.html.erb
<h3>User Profile</h3><br>

   <%= form_tag("/recipes/updateprofile"  , :method=>"post" , :multipart=> true ) do  %>
   <div class="form-group">
   <table>
   <tr>
   <th>Email:</th>
   <td><input type="text" class="form-control" value="<%= current_user.email %>" name="email"/></td>
   
   </tr>
   <tr><th>&nbsp;</th><td>&nbsp;</td></tr>
   <tr>
   <th>Address:</th>
   <td>
<input type="text" class="form-control"  name="address" value="<%= current_user.address %>"/>
</td>
   </tr>
     <tr><th>&nbsp;</th><td>&nbsp;</td></tr>
    <tr>
   <th>Interests:</th>
 <td>
<input type="text" class="form-control"  name="hobbies" value="<%= current_user.hobbies %>"/>
    </td>
   </tr>
    <tr><th>&nbsp;</th><td>&nbsp;</td></tr>
   <tr>
   <th>Profile Pic:</th>
   <td><% if current_user.pic.exists? %>
        <%= image_tag current_user.pic.url %>
        <%= image_tag current_user.pic.path %>
    <% end %>
  

      <%= file_field_tag :pic %>
   </td>
   </tr>
   </table><br><br>
 </div> 
<%=  submit_tag "SAVE" , :class=>"btn btn-warning" %>
<% end %>

app/views/recipes/updateprofile.html.erb
<h3>User Profile </h3>
<br>

<table class="table table-hover">
<tr>
<th>Email:</th><td><%= current_user.email %> </td>
<td>
 </td>
</tr>
<tr>
<th>Address:</th><td><%= current_user.address %></td>
</tr>

<tr>
<th>Hobbies:</th><td> <%= current_user.hobbies %></td>
</tr>

<tr>
<th>Profile Pic:</th><td> <%= image_tag current_user.pic.url %></td>
</tr>
</table>

app/views/recipes/view_category.html.erb
<h1>Choose categories</h1>
<% @categories.each do |category| %>
<li class="col-sm-4">
<div class="thumbnails">
  
<h2> 
 
<b><%= link_to "#{category.name}" , list_recipe_items_path(:id => category.id) %></h2></b>
     <h4 class="tag">Find unique dishes in this category</h4>   

    
</div>
 
<br>

<% end %>
</li>
<br/>

app/views/recipes/view_recipe.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @item.item_name %>
</p>