config/routes.rb
RecipeBook::Application.routes.draw do

  devise_for :users

resources :welcome_mailer do
 collection do
  post 'welcome'
 end
end 

resources :items do 
  collection do
    get '_dashboard'
    get 'list_recipe'
    get '_panel'
    post 'mailer'
    get 'like_count'
  end
end
  resources :admin do
    collection do
      get 'items'
      get 'home'
      get 'categories'
      get 'list_recipe'
      get 'show'
      get 'my_recipe'
      get '_panel'
      
    end
  end

 resources :recipes do
   collection do
     get 'view_category'
     get 'view_recipe'
     get 'home'
     get 'my_recipe'
     get 'profile'
     post 'updateprofile'
     get '_search'
   end
 end

  resources :categories do
    collection do
      get 'home'
    end
  end

 

  

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :item_name, :category_id , :pic , :description
  belongs_to :category
  belongs_to :user
  has_attached_file :pic, :styles => 
           { :medium => "300x300>", :thumb => "100x100>" }
  do_not_validate_attachment_file_type :pic
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
 
   def index
    @items = Item.all
    if !params[:search].blank?
    @items = Item.where(:item_name => params[:search])
    end
      @user = User.all
       respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end
  
   def _panel
     
   end
  
  def home
    
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    
    @item = Item.find(params[:id])
   # @item.user_id==current_user.id
      
      respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
   
 end
 

 def like_count
  item = Item.find(params[:id])
  item.increment(:likes)
  item.save
  redirect_to :action=>'show' , :id=>item
end

 
  
  def list_recipe
    @list_recipe= params[:id]
    @category= Category.find(params[:id])
    @recipe= Item.where(:category_id => @list_recipe)
  end

  
  def _dashboard
    
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @item = Item.new
    if !current_user
     flash[:notice]="Please sign-in to add recipe !"
     redirect_to home_recipes_path
     return
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /categories/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @item = Item.new(params[:item])
    @item.user_id = current_user.id      
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end


 


  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_dashboard.html.erb
<ol class="breadcrumb">
 <li> <b><a href="/items">View Recipes</a></b></li>
  <li class="active"><b><a href="/items/new">Add Recipies</a></b></li>
  
</ol>

app/views/items/_form.html.erb
<%= tinymce_assets %><%= tinymce %>
<%= form_for @item , :html => { :multipart => true } do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="form-group">
    <%= f.label :category %><br />
  <%= collection_select(:item, :category_id, Category.all, :id, :name, {:prompt => false }, {:class=>"form-control"})  %>
   </div>
  <div class="form-group">
    <%= f.label :item_name %><br />
    <%= f.text_field :item_name , :class=>"form-control"%>
  </div>
 <div class="form-group">
    <%= f.label :pic %><br />
    <%= f.file_field :pic %>
  </div>
 <div class="form-group">
    <%= f.label :description %><br />
    <%= f.text_area :description , :class => "tinymce" , :rows=>9 , :cols=>20 %>
  </div> 
    
   <div class="actions">
     <%= submit_tag "CREATE RECIPE" , :class=>"btn btn-warning"  %></p>
  </div>
<% end %>

app/views/items/_panel.html.erb
<div class="panel panel-warning">
<h5>
<%= link_to '<- My Recipies', my_recipe_recipes_path %> | 
<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Destroy', @item , method: :delete, data: { confirm: 'Are you sure?' } %>
  </h5>
</div>

app/views/items/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<%= render 'dashboard' %> <h1>Recipies</h1>

<% @items.each do |item| %>
<div id="recipe_list">
<table>

<tr>
<th><%= image_tag item.pic.url(:thumb)%></th> 
<td>&nbsp;</td> <td>&nbsp;</td> 
<td><h2 class="item_name"><td><b><%= link_to "#{item.item_name}" , item_path(item.id) %></h2></b>
<h5>
<% @user=User.where(:id=>item.user_id) %>
<% @user.each do |user| %>
<%= user.email %>
<% end %>
</h5>
<i><%= item.created_at.to_s %></i></td>
</tr>
<tr><th>&nbsp;</th><td>&nbsp;</td></tr>
</table>

 <div class="social-icons">
  Share recipe
 <button onclick="document.location.href='<%= item_path(item.id)%>'"> <img src="/assets/gmail.png" /></button>
 </div>
</div>  
<% end %>
<br />

app/views/items/list_recipe.html.erb
<h2> <%= @category.name  %> Recipies </h2>

<br><br>

<% @recipe.each do |recipe| %>

 
<div id="recipe_list">
<table>

<tr>
<th><%= image_tag recipe.pic.url(:thumb)%></th> 
<td>&nbsp;</td> <td>&nbsp;</td> 
<td><h2 class="item_name"><td><b><%= link_to "#{recipe.item_name}" , item_path(recipe.id) %> </h2></b>
<h5>
<% @user=User.where(:id=>recipe.user_id) %>
<% @user.each do |user| %>
<%= user.email %>
<% end %>
</h5>
<i><%= recipe.created_at.to_s %></i></td>
</tr>
<tr><th>&nbsp;</th><td>&nbsp;</td></tr>

</table>
<div class="social-icons">
 Share Recipe
<button onclick="document.location.href='<%= item_path(recipe.id)%>'"> <img src="/assets/gmail.png" /></button>
 </div>
</div>  
<% end %>
<br />

app/views/items/new.html.erb
<h1>New Recipe</h1>
<%= render 'dashboard' %>
<%= render 'form' %>

app/views/items/show.html.erb
<hr>
<ol class="breadcrumb">
 <li><a href="/recipes/view_category">< Choose Category</a></li>
 
</ol>
<p id="notice"><%= notice %></p>
<% if current_user %>
<% if @item.user_id == current_user.id %>
<%= render 'panel' %>
<% end %>
<% end %>
  <b>Name:</b>
  <%= @item.item_name %><br><br>
  <b>Pic:</b>  <%= image_tag(@item.pic.url) %><br><br>
   <b>Description:</b> <%= @item.description.to_s.html_safe %><br><br>
</p>

<br><br>
<b>Rate the Recipe:</b>&nbsp;
<img src="/assets/like.jpeg" width="30" height="30"/>
<th><%= link_to "LIKE", {:action => 'like_count', :id => @item.id } %></th>
<span class="badge"><%= @item.likes %></span>

<br><br>

<b> Share The Recipe with your friends: </b><br>
<%= form_tag("/welcome_mailer/welcome" , :method=>"post") do %>
<input type="text" placeholder="Enter Email" name="email"/>
<input type="hidden" value="<%= @item.id %>" name="body"/><br>
<%=  submit_tag "SHARE" , :class=>"btn btn-warning" %>
<% end %>