config/routes.rb
RecipeBook::Application.routes.draw do

  devise_for :users

resources :welcome_mailer do
 collection do
  post 'welcome'
 end
end 

resources :items do 
  collection do
    get '_dashboard'
    get 'list_recipe'
    get '_panel'
    post 'mailer'
    get 'like_count'
  end
end
  resources :admin do
    collection do
      get 'items'
      get 'home'
      get 'categories'
      get 'list_recipe'
      get 'show'
      get 'my_recipe'
      get '_panel'
      
    end
  end

 resources :recipes do
   collection do
     get 'view_category'
     get 'view_recipe'
     get 'home'
     get 'my_recipe'
     get 'profile'
     post 'updateprofile'
     get '_search'
   end
 end

  resources :categories do
    collection do
      get 'home'
    end
  end

 

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :items
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  before_filter :check_user , :only =>[:new , :create , :edit , :update , :destroy , :index , :show , :home]
layout 'standard'
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end
  
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  
  def edit
    @category = Category.find(params[:id])
  end
    
    def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
  
  def home
    
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

protected
def check_user
  if !current_user
    flash[:notice]="You are not authorized to view this page !"
    redirect_to home_recipes_path
    return
  end
  if current_user.role=="user"
    flash[:notice]= "You are not authorized to view this page !"
    redirect_to home_recipes_path
  end
end


end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  </div><div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/home.html.erb
<div class="wrapper">
                 <div id="pics"> 
                 <img src="/assets/food1.jpeg" /> 
                  <img src="/assets/food2.jpeg" /> 
                  <img src="/assets/food3.jpeg" /> 
                 </div>
                     <div class="ribbon-wrapper-green">
                     <div class="ribbon-green">NEW</div>
                     
                  
      </div>
      </div>

app/views/categories/index.html.erb
<h1>Listing Categories</h1>

<table>
  <tr>
    <th>Name</th>
  
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= link_to "#{category.name}" , items_path(:id => category.id) %></td>
     </tr>
<% end %>
</table>

<br />

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>